project:
  type: book

book:
  title: "snap-manual"
  author: Brian Harvey
  date: 11/12/2024
  page-navigation: true
  chapters:
    - index.qmd
    - part: content/Chapter1.md
      chapters:
      - content/C1-S1.md
      - content/C1-S2.md
      - content/C1-S3.md
      - content/C1-S4.md
      - content/C1-S5.md
      - content/C1-S6.md
      - content/C1-S7.md
      - content/C1-S8.md
      - content/C1-S12.md
      - content/C1-S13.md
      # - content/C1-S14.md
      - content/C1-S15.md
      - content/C1-S16.md
      - content/C1-S17.md
      - content/C1-S18.md
    - content/Chapter2.md


# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
