project:
  type: book
  output-dir: _book
  # resources:
  preview:
    port: 8081
    browser: true
  # pre-render:
  # post-render:

book:
  title: Snap! Reference Manual
  output-file: snap-manual
  author: Brian Harvey & Jens Mönig
  date: May 8, 2025
  description: A manual for Snap! TODO
  references: references.bib
  cover-image: images/cover-image.png
  cover-image-alt: Snap! Manual Cover Image TODO
  favicon: images/snap-logo.png
  language: en
  edition: 10
  license: CC-BY-NC-SA 4.0
  url: https://snap-cloud.github.io/manual/
  public-url: https://snap-cloud.github.io/manual/
  # TODO: Should we auto-commit this to the snap repo?
  pdf-url: https://snap.berkeley.edu/snap/help/SnapManual.pdf
  # doi:
  # abstract:
  downloads:
    - pdf
    # - epub
  page-navigation: true
  search: true
  navbar:
    pinned: true
    logo: images/snap-logo.png
    logo-alt: Snap! Logo
    logo-href: https://snap-cloud.github.io/manual/
    tools:
  # sidebar:
    # style: "docked"
    # search: true
  repo-url: https://github.com/snap-cloud/manual/
  repo-actions: [edit]
  chapters:
    - index.qmd
    - content/00-acknowledgements/index.md
    - content/01-blocks-scripts-and-sprites/index.md
    - content/02-saving-and-loading-projects-and/index.md
    - content/03-building-a-block/index.md
    - content/04-first-class-lists/index.md
    - content/05-typed-inputs/index.md
    - content/06-procedures-as-data/index.md
    - content/07-object-oriented-programming-with-sprites/index.md
    - content/08-oop-with-procedures/index.md
    - content/09-the-outside-world/index.md
    - content/10-continuations/index.md
    - content/11-metaprogramming/index.md
    - content/12-user-interface-elements/index.md
    # This stuff is duplicative of Chapter 1 and 2 above.
    #- part: content/Chapter1.md
    #  chapters:
    #  - content/C1-S1.md
    #  - content/C1-S2.md
    #  - content/C1-S3.md
    #  - content/C1-S4.md
    #  - content/C1-S5.md
    #  - content/C1-S6.md
    #  - content/C1-S7.md
    #  - content/C1-S8.md
    #  - content/C1-S12.md
    #  - content/C1-S13.md
    #  - content/C1-S14.md
    #  - content/C1-S15.md
    #  - content/C1-S16.md
    #  - content/C1-S17.md
    #  - content/C1-S18.md
    #- content/Chapter2.md
  appendices:
    - content/13-appendix-a-snap-color-library/index.md
    - content/14-appendix-b-apl-features/index.md
    - content/15-appendix-c-blocks-index/index.md
    - references.qmd
    - content/index-list.qmd


bibliography: references.bib
# Don't number subsections as chapters.
number-depth: 1

format:
  html:
    toc: true
    roman-numerals: true
    section-numbering:
      style: roman
      roman-numerals: true
    filters:
      - scripts/collect-index.lua
    # output-file: snap-manual
    theme: [none, styles/snap-manual.scss]
    strip-comment: true
    html-math-method: katex
    navbar:
      logo: images/snap-logo.png
    # include-in-header:
    #   - text: |
    #       <script src="https://examples.org/demo.js"></script>
    #   - file: analytics.html
    #   - comments.html
    # include-before-body: header.html
  # epub:
  #   css: styles/epub.css
  #   cover-image: cover.png
  pdf:
    lang: en
    dir: ltr
    # https://quarto.org/docs/reference/formats/pdf.html
    output-file: snap-manual.pdf
    cover-image: images/cover-image.png
    # Do not use pdflatex since we have unicode chars
    pdf-engine: lualatex # wkhtmltopdf # xelatex # or lualatex
    # pdf-engine-opt:
    keep-tex: false
    # This are necessary to make an index.
    include-in-header: styles/latex-preamble.tex
    include-after-body:
      text: |
        \printindex
    toc: true
    number-sections: true
    number-depth: 1
    documentclass: book
    papersize: letter
    # mainfont: Baskerville
    monofont: Source Code Pro
    sansfont: Helvetica
    resource-path:
      - ./
      - content/assets/
      - content/assets/images/
      # - content/00-acknowledgements/assets/
      # - content/01-blocks-scripts-and-sprites/assets/
      # - content/02-saving-and-loading-projects-and/assets/
      # - content/03-building-a-block/assets/
      # - content/04-first-class-lists/assets/
      # - content/05-typed-inputs/assets/
      # - content/06-procedures-as-data/assets/
      # - content/07-object-oriented-programming-with-sprites/assets/
      # - content/08-oop-with-procedures/assets/
      # - content/09-the-outside-world/assets/
      # - content/10-continuations/assets/
      # - content/11-metaprogramming/assets/
      # - content/12-user-interface-elements/assets/
      # - content/13-appendix-a-snap-color-library/assets/
      # - content/14-appendix-b-apl-features/assets/
      # - content/15-appendix-c-blocks-index/assets/
