project:
  type: book
  output-dir: _book
  preview:
    port: 8081
    browser: true
    watch-inputs: false
    navigate: false
  # These files are included in the published website.
  resources:
    - CNAME
    - LICENSE
    - README.md
  # pre-render:
  #   - blocks/render-block-files.py
  # post-render:

bibliography: references.bib
# Don't number subsections as chapters.
number-depth: 1
# Setting toc-depth to 1 disables displaying the pre-page toc
# toc-depth: 1
# appendix-style: none

format:
  html:
    aria: true # requires quarto-dev / v1.8+
    toc: true
    roman-numerals: true
    section-numbering:
      style: roman
      roman-numerals: true
    filters:
      - scripts/collect-index.lua
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    theme:
      - default
      - styles/snap-manual.scss
    fontsize: 16px
    # mainfont:
    # monofont:
    respect-user-color-scheme: true
    strip-comment: true
    html-math-method: katex
    # TODO: Add link to s.b.e
    #
    navbar:
      logo: images/snap-logo.png
      logo-alt: Snap! Logo
    # include-in-header:
    #   - text: |
    #       <script src="https://examples.org/demo.js"></script>
    #   - file: analytics.html
    #   - comments.html
    include-after-body:
      - text: |
          <script>
            const nav = document.querySelector('nav');
            nav.insertAdjacentHTML('afterend', '<div class="trapezoid"></div>');
          </script>
    # TODO: Customize footer. Add berkeley + SAP links.
  # epub:
  #   css: styles/epub.css
  #   cover-image: cover.png
  pdf:
    lang: en
    dir: ltr
    # https://quarto.org/docs/reference/formats/pdf.html
    output-file: snap-manual.pdf
    cover-image: images/cover-image.png
    # Do not use pdflatex since we have unicode chars
    pdf-engine: lualatex # wkhtmltopdf # xelatex # or lualatex
    # pdf-engine-opt:
    keep-tex: false
    # This are necessary to make an index.
    include-in-header: styles/latex-preamble.tex
    include-after-body:
      text: |
        \printindex
    toc: true
    number-sections: true
    number-depth: 1
    documentclass: scrreprt # book
    papersize: letter
    # TODO: In order to enable fonts, they need to be added to the GitHub Workflow.
    # mainfont: Baskerville
    # monofont: Source Code Pro
    # sansfont: Helvetica
    resource-path:
      - ./
      - content/assets/
      - content/assets/images/
      - blocks/images/
      - blocks/help/

book:
  title: Snap<em>!</em> Reference Manual
  output-file: snap-manual
  author: Brian Harvey, Jens Mönig, Michael Ball, Jadga Hügle, Victoria Phelps, Bernat Romagosa
  date: May 8, 2025
  description: A manual for Snap!
  references: references.bib
  cover-image: images/cover-image.png
  cover-image-alt: Snap! Manual Cover Image
  favicon: images/favicon.png
  language: en
  edition: 11
  license: CC-BY-NC-SA 4.0
  url: https://docs.snap.berkeley.edu/
  public-url: https://docs.snap.berkeley.edu/
  pdf-url: https://snap.berkeley.edu/snap/help/SnapManual.pdf
  # doi:
  # abstract:
  downloads:
    - pdf
    # - epub
  page-navigation: true
  search: true
  navbar:
    pinned: true
    logo: images/snap-logo.png
    logo-alt: Snap! Logo
    logo-href: https://docs.snap.berkeley.edu/
    # tools:
  sidebar:
    style: "docked"
    search: true
  repo-url: https://github.com/snap-cloud/manual/
  issue-url: https://forum.snap.berkeley.edu/c/manual/77
  repo-actions: none # [edit]
  chapters:
    - index.qmd
    - content/00-acknowledgements/index.md
    - content/01-blocks-scripts-and-sprites/index.md
    - content/02-saving-and-loading-projects-and/index.md
    - content/03-building-a-block/index.md
    - content/04-first-class-lists/index.md
    - content/05-typed-inputs/index.md
    - content/06-procedures-as-data/index.md
    - content/07-object-oriented-programming-with-sprites/index.md
    - content/08-oop-with-procedures/index.md
    - content/09-the-outside-world/index.md
    - content/10-continuations/index.md
    - content/11-metaprogramming/index.md
    - content/12-user-interface-elements/index.md
    - content/13-community-site/index.md
  appendices:
    - content/13-appendix-a-snap-color-library/index.md
    - content/14-appendix-b-apl-features/index.md
    - blocks/index.md
    - part: Motion Blocks
      chapters:
        - blocks/motion/forward.qmd
        - blocks/motion/turn.qmd
        - blocks/motion/turnLeft.qmd
        - blocks/motion/setHeading.qmd
        - blocks/motion/doFaceTowards.qmd
        - blocks/motion/gotoXY.qmd
        - blocks/motion/doGotoObject.qmd
        - blocks/motion/doGlide.qmd
        - blocks/motion/changeXPosition.qmd
        - blocks/motion/setXPosition.qmd
        - blocks/motion/changeYPosition.qmd
        - blocks/motion/setYPosition.qmd
        - blocks/motion/bounceOffEdge.qmd
        - blocks/motion/getPosition.qmd
        - blocks/motion/xPosition.qmd
        - blocks/motion/yPosition.qmd
        - blocks/motion/direction.qmd
    - part: Looks Blocks
      chapters:
        - blocks/looks/doSwitchToCostume.qmd
        - blocks/looks/doWearNextCostume.qmd
        - blocks/looks/getCostumeIdx.qmd
        - blocks/looks/doSayFor.qmd
        - blocks/looks/bubble.qmd
        - blocks/looks/doThinkFor.qmd
        - blocks/looks/doThink.qmd
        - blocks/looks/reportGetImageAttribute.qmd
        - blocks/looks/reportNewCostumeStretched.qmd
        - blocks/looks/reportNewCostumeSkewed.qmd
        - blocks/looks/reportNewCostume.qmd
        - blocks/looks/changeEffect.qmd
        - blocks/looks/setEffect.qmd
        - blocks/looks/clearEffects.qmd
        - blocks/looks/getEffect.qmd
        - blocks/looks/changeScale.qmd
        - blocks/looks/setScale.qmd
        - blocks/looks/getScale.qmd
        - blocks/looks/show.qmd
        - blocks/looks/hide.qmd
        - blocks/looks/reportShown.qmd
        - blocks/looks/goToLayer.qmd
        - blocks/looks/goBack.qmd
    - part: Sound Blocks
      chapters:
        - blocks/sound/playSound.qmd
        - blocks/sound/doPlaySoundUntilDone.qmd
        - blocks/sound/doStopAllSounds.qmd
        - blocks/sound/doPlaySoundAtRate.qmd
        - blocks/sound/reportGetSoundAttribute.qmd
        - blocks/sound/reportNewSoundFromSamples.qmd
        - blocks/sound/doRest.qmd
        - blocks/sound/doPlayNote.qmd
        - blocks/sound/doSetInstrument.qmd
        - blocks/sound/doChangeTempo.qmd
        - blocks/sound/doSetTempo.qmd
        - blocks/sound/getTempo.qmd
        - blocks/sound/changeVolume.qmd
        - blocks/sound/setVolume.qmd
        - blocks/sound/getVolume.qmd
        - blocks/sound/changePan.qmd
        - blocks/sound/setPan.qmd
        - blocks/sound/getPan.qmd
        - blocks/sound/playFreq.qmd
        - blocks/sound/stopFreq.qmd
    - part: Pen Blocks
      chapters:
        - blocks/pen/clear.qmd
        - blocks/pen/down.qmd
        - blocks/pen/up.qmd
        - blocks/pen/getPenDown.qmd
        - blocks/pen/setColor.qmd
        - blocks/pen/changePenColorDimension.qmd
        - blocks/pen/setPenColorDimension.qmd
        - blocks/pen/getPenAttribute.qmd
        - blocks/pen/changeSize.qmd
        - blocks/pen/setSize.qmd
        - blocks/pen/doStamp.qmd
        - blocks/pen/floodFill.qmd
        - blocks/pen/write.qmd
        - blocks/pen/reportPenTrailsAsCostume.qmd
        - blocks/pen/doPasteOn.qmd
        - blocks/pen/doCutFrom.qmd
        - blocks/pen/reportColor.qmd
        - blocks/pen/reportColorAttribute.qmd
        - blocks/pen/reportNewColor.qmd
    - part: Control Blocks
      chapters:
        - blocks/control/receiveGo.qmd
        - blocks/control/receiveUserEdit.qmd
        - blocks/control/receiveOnClone.qmd
        - blocks/control/receiveMessage.qmd
        - blocks/control/receiveKey.qmd
        - blocks/control/receiveConditionEvent.qmd
        - blocks/control/receiveInteraction.qmd
        - blocks/control/doBroadcast.qmd
        - blocks/control/doBroadcastAndWait.qmd
        - blocks/other/doWarp.qmd
        - blocks/control/doWait.qmd
        - blocks/control/doWaitUntil.qmd
        - blocks/control/doForever.qmd
        - blocks/control/doRepeat.qmd
        - blocks/control/doUntil.qmd
        - blocks/control/doFor.qmd
        - blocks/control/doIf.qmd
        - blocks/control/doIfElse.qmd
        - blocks/control/reportIfElse.qmd
        - blocks/control/doReport.qmd
        - blocks/control/doStopThis.qmd
        - blocks/control/doRun.qmd
        - blocks/control/fork.qmd
        - blocks/control/evaluate.qmd
        - blocks/control/reportPipe.qmd
        - blocks/control/doTellTo.qmd
        - blocks/control/reportAskFor.qmd
        - blocks/control/createClone.qmd
        - blocks/control/newClone.qmd
        - blocks/control/removeClone.qmd
        - blocks/control/doPauseAll.qmd
        - blocks/control/doSwitchToScene.qmd
        - blocks/control/doDefineBlock.qmd
        - blocks/control/doDeleteBlock.qmd
        - blocks/control/doSetBlockAttribute.qmd
        - blocks/control/reportBlockAttribute.qmd
        - blocks/control/reportEnvironment.qmd
        - blocks/control/doSetSlot.qmd
    - part: Sensing Blocks
      chapters:
        - blocks/sensing/reportTouchingObject.qmd
        - blocks/sensing/reportTouchingColor.qmd
        - blocks/sensing/reportColorIsTouchingColor.qmd
        - blocks/sensing/doAsk.qmd
        - blocks/sensing/getLastAnswer.qmd
        - blocks/sensing/reportMousePosition.qmd
        - blocks/sensing/reportMouseX.qmd
        - blocks/sensing/reportMouseY.qmd
        - blocks/sensing/reportMouseDown.qmd
        - blocks/sensing/reportKeyPressed.qmd
        - blocks/sensing/reportRelationTo.qmd
        - blocks/sensing/reportAspect.qmd
        - blocks/sensing/doResetTimer.qmd
        - blocks/sensing/getTimer.qmd
        - blocks/sensing/reportDate.qmd
        - blocks/sensing/reportAttributeOf.qmd
        - blocks/sensing/reportGet.qmd
        - blocks/sensing/reportObject.qmd
        - blocks/sensing/reportURL.qmd
        - blocks/sensing/reportAudio.qmd
        - blocks/sensing/reportVideo.qmd
        - blocks/sensing/doSetVideoTransparency.qmd
        - blocks/sensing/reportGlobalFlag.qmd
        - blocks/sensing/doSetGlobalFlag.qmd
    - part: Operators Blocks
      chapters:
        - blocks/other/reifyScript.qmd
        - blocks/other/reifyReporter.qmd
        - blocks/other/reifyPredicate.qmd
        - blocks/operators/reportVariadicSum.qmd
        - blocks/operators/reportDifference.qmd
        - blocks/operators/reportVariadicProduct.qmd
        - blocks/operators/reportQuotient.qmd
        - blocks/operators/reportPower.qmd
        - blocks/operators/reportModulus.qmd
        - blocks/operators/reportVariadicMin.qmd
        - blocks/operators/reportVariadicMax.qmd
        - blocks/operators/reportRound.qmd
        - blocks/operators/reportMonadic.qmd
        - blocks/operators/reportAtan2.qmd
        - blocks/operators/reportRandom.qmd
        - blocks/operators/reportVariadicLessThan.qmd
        - blocks/operators/reportVariadicEquals.qmd
        - blocks/operators/reportVariadicGreaterThan.qmd
        - blocks/operators/reportVariadicAnd.qmd
        - blocks/operators/reportVariadicOr.qmd
        - blocks/operators/reportNot.qmd
        - blocks/operators/reportBoolean.qmd
        - blocks/operators/reportJoinWords.qmd
        - blocks/operators/reportTextSplit.qmd
        - blocks/operators/reportLetter.qmd
        - blocks/operators/reportTextAttribute.qmd
        - blocks/operators/reportUnicode.qmd
        - blocks/operators/reportUnicodeAsLetter.qmd
        - blocks/operators/reportIsA.qmd
        - blocks/operators/reportVariadicIsIdentical.qmd
    - part: Variables Blocks
      chapters:
        - blocks/variables/doSetVar.qmd
        - blocks/variables/doChangeVar.qmd
        - blocks/variables/doShowVar.qmd
        - blocks/variables/doHideVar.qmd
        - blocks/other/doDeclareVariables.qmd
        - blocks/variables/doDeleteAttr.qmd
        - blocks/lists/reportNewList.qmd
        - blocks/lists/reportNumbers.qmd
        - blocks/lists/reportCONS.qmd
        - blocks/lists/reportListItem.qmd
        - blocks/lists/reportCDR.qmd
        - blocks/lists/reportListAttribute.qmd
        - blocks/lists/reportListIndex.qmd
        - blocks/lists/reportListContainsItem.qmd
        - blocks/lists/reportListIsEmpty.qmd
        - blocks/lists/reportMap.qmd
        - blocks/lists/reportKeep.qmd
        - blocks/lists/reportFindFirst.qmd
        - blocks/lists/reportCombine.qmd
        - blocks/lists/doForEach.qmd
        - blocks/lists/doAddToList.qmd
        - blocks/lists/doDeleteFromList.qmd
        - blocks/lists/doInsertInList.qmd
        - blocks/lists/doReplaceInList.qmd
        - blocks/lists/reportConcatenatedLists.qmd
        - blocks/lists/reportReshape.qmd
        - blocks/lists/reportCrossproduct.qmd
    - part: Advanced and Hidden Blocks
      chapters:
        - blocks/operators/reportJSFunction.qmd
        - blocks/other/doPrimitive.qmd
        - blocks/other/doApplyExtension.qmd
        - blocks/other/reportApplyExtension.qmd
    # - references.qmd
    # - content/index-list.qmd
