# Introduction {.unnumbered .unlisted}

<!--
  This is the first page of the Snap! Manual.
  The manual title is already included on the top of this page by Quarto.

  We need to include some title, but don't want it to be redundant.
-->
Welcome to the Snap*!* manual. This manual is a newly updated version. However, there are still many images and pages that need proper formatting.

You may wish to [download a pdf][pdf] of the manual.

[pdf]: https://snap.berkeley.edu/snap/help/SnapManual.pdf

\index{home}

The manual is roughly organized into a few sections.

* Chapters 1 to 11 cover the primary features for writing programings in
Snap*!*. They are organized from introductory to advanced topics.
* Chapters 12 and 13 cover the user interface components of both the Snap*!* editor and the community site.
* The appendicies provide [documentation for every block in Snap*!*][blocks], as well as some of libraries provided.

[blocks]: /blocks/

<!-- TODO: Index and references? -->

<!-- TODO: Hide this from the PDF. -->
::: {.content-visible when-format="html"}
## Features of the Manual

You'll find the table of contents on the left side of each page. At the bottom of each page, you'll find previous and next links to navigate the manual in order.

A search function is included in the upper right hand corner. If you which you can type <kbd>/</kbd> (or <kbd>?</kbd>) to jump to the search function.
:::

::: {.content-visible when-format="pdf"}
## The 'New' PDF Manual {.unnumbered .unlisted}

this is currently a work in progress.
:::
