on:
  workflow_dispatch:
  push:
    branches:
      - main
      - quarto

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install necessary APT packages
        run: |
          sudo apt-get update
          sudo apt install ttf-mscorefonts-installer
          sudo apt-get install -y texlive-latex-extra texlive-luatex
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # with:
        #   # To install LaTeX to build PDF book
        #   tinytex: true
      - name: Debugging
        run: |
          echo "Quarto version:"
          quarto --version
          echo "Python version:"
          python --version
          echo "Quarto config:"
          quarto list tools
          echo "Listing known fonts"
          fc-list
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install jupyter
      - name: Render Book project
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: 'github'
        # with:
        #   to: html pdf
      - name: Publish HTML book
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
